const keywords = [
  "anime",
  "recommendations",
  "AI-powered",
  "personalized",
  "viewing history",
  "preferences",
  "selection",
  "user-friendly",
  "cutting-edge technology",
  "binge-worthy",
  "streaming",
  "watch",
  "episodes",
  "series",
  "top-rated",
  "popular",
  "new releases",
  "classics",
  "manga",
  "fanservice",
  "subbed",
  "dubbed",
  "action",
  "adventure",
  "romance",
  "comedy",
  "drama",
  "fantasy",
  "sci-fi",
  "horror",
  "shounen",
  "shoujo",
  "seinen",
  "josei",
  "moe",
  "otaku",
  "cosplay",
  "merchandise",
  "community",
  "forums",
  "reviews",
  "ratings",
  "news",
  "updates",
  "events",
];

export const siteConfig = {
  name: "AnimRev",
  url: "https://anim.rev",
  ogImage: "https://anim.rev/og.jpg",
  description:
    "Find the perfect anime for you with our AI-powered recommendation engine. Our site offers personalized recommendations based on your viewing history and preferences. With a vast selection of top-rated and popular anime titles, including new releases and classics, you're sure to find your next binge-worthy series. Our user-friendly interface and cutting-edge technology make it easy to watch your favorite anime episodes, whether subbed or dubbed. Join our community of anime fans and stay up-to-date with the latest news, reviews, and updates. Start your anime journey today!",
  links: {
    twitter: "https://twitter.com/animrev",
    github: "https://github.com/matannahmani/animrev",
  },
  keywords,
};

export type SiteConfig = typeof siteConfig;
